# docker-composeのバージョン指定
version: '3.8'

# コンテナ群の記述
services:
  # nginxというサービス
  nginx:
    # コンテナ名指定
    container_name: curriculum-nginx
    # 使用イメージの指定
    image: nginx:latest
    # 同期ファイルの指定
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./app/public:/var/www/html
    # 使用ポートの指定
    ports:
      - "80:80"
    # 依存関係の指定 (指定したコンテナより後に立ち上がる)
    depends_on:
      - php

  php:
    container_name: curriculum-laravel
    ###############################################################
    # Mac M1チップユーザーは以下のコメントアウトを解除して作業を進めてください
    # platform: linux/x86_64
    ###############################################################
    
    # どれを使ってビルド(コンテナ立ち上げを行うか)
    build: 
      # ディレクトリの指定
      context: ./
      # 使用するDockerfile名の指定
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/check_startup.sh:/tmp/check_startup.sh
    # サーバーに対してオープンするポートを指定
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: curriculum-db
    hostname: curriculum-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root


  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    # コンテナの関連を指定
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions